### ISSUE TITLE
[security] add origin check to prevent database update from remote

### ISSUE THREAD

**Issue by jibe-b** [CottageLabs/api#19]
@markmacgillivray as you state in oabutton/discussion#802, a local instance of OAB with valid credentials would access the API.

This is a security risk.

The API should check the origin of a request to only accept those from openaccessbutton.org

**Comment by markmacgillivray** [comment]
Sorry, but I'm not sure you understand the purpose of an API. This relates to the discussion about putting all the code in one place too. This API is NOT a website. It's an API, and it's accessed by many different services, ONE of which is a website. 

It doesn't matter whether you login from a local copy, from the live site, from the plugin, from a bookmarklet, from a command line... Wherever you login from, then of course you have the same power to edit anything that you could edit from the website.

If we applied an origin policy to the API, we would break the majority of the use cases.

**Comment by jibe-b** [comment]
Ok, fine. I made a mistake in using the word _security_ when you only gave me a warning on the risk to update the database.

It's up to you to have an origin policy. On my side, tests will be on a test instance of the CL API, or at least what constitutes the backend of OAB, in the case it can be modularised.

**Comment by markmacgillivray** [comment]
But why waste your time running the api locally, or even considering modularising the oabutton code? I still don't understand why you think that is necessary to develop the website repo.
